### PR TITLE
new changes - camera and gun viewports working fixes 

### PR DESCRIPTION
**Pull request by OleMortensen8**
provided me a description of what you changed.

### CODE REVIEW

**Comment by OleMortensen8** [comment]
This branch is not ready for Review yet.

**Review by subtostrikeman — APPROVED** [review]
nice

**Review by OleMortensen8 — COMMENTED** [review]
@subtostrikeman can't aprove

**Comment by subtostrikeman** [comment]
i can not aprove this becouse i am the last pusher

**Comment by OleMortensen8** [comment]
I'll look at this!

**Review by subtostrikeman — APPROVED** [review]

**Comment by OleMortensen8** [comment]
You'll need to downgrade 4.0 as it's the only stable version I have on my machine can harbor misguided results. 
yet, I found:

- only the A key worked. horrible display.

**Review by OleMortensen8 — COMMENTED** [review]
my results  failed movements they're still not fixed

**Pull request merged**
